Repository aeecleclair/Hyperion, pull requests merged in 2022-12, with the labels that each got.

#87 Repair get user manageable loans
  app/endpoints/loans.py
Labels: bug, module

#84 Amap cash debug
  app/cruds/cruds_amap.py
  app/endpoints/amap.py
  app/models/models_amap.py
  app/schemas/schemas_amap.py
  tests/test_amap.py
Labels: bug

#86 AMAP: Add an `order` relationship to deliveries
  app/cruds/cruds_amap.py
  app/endpoints/amap.py
  app/models/models_amap.py
  app/schemas/schemas_amap.py
Labels: bug, module

#98 User creation mail message and token size
  app/core/security.py
  app/endpoints/users.py
Labels: core
