Repository aeecleclair/Hyperion, pull requests merged in 2022-10, with the labels that each got.

#47 Users management
  app/cruds/cruds_users.py
  app/endpoints/auth.py
  app/endpoints/users.py
  app/schemas/schemas_core.py
  app/utils/examples/examples_core.py
  app/utils/types/standard_responses.py
  templates/activation.html
  templates/error.html
  tests/test_auth.py
  tests/test_users.py
Labels: core

#48 Booking module
  README.md
  app/api.py
  app/cruds/cruds_bdebooking.py
  app/cruds/cruds_calendar.py
  app/endpoints/bdebooking.py
  app/endpoints/bdecalendar.py
  app/endpoints/calendar.py
  app/main.py
  app/models/models_bdebooking.py
  app/models/models_calendar.py
  app/schemas/schemas_bdebooking.py
  app/schemas/schemas_calendar.py
  app/utils/types/bdebooking_type.py
  app/utils/types/calendar_types.py
  app/utils/types/groups_type.py
  app/utils/types/tags.py
  requirements.txt
  tests/test_bdebooking.py
  tests/test_calendar.py
Labels: module

#73 Return a 204 http code when succeeding a PATCH request
  app/endpoints/bdebooking.py
  app/endpoints/users.py
  tests/test_bdebooking.py
  tests/test_users.py
Labels: bug
