Repository aeecleclair/Hyperion, pull requests merged in 2023-08, with the labels that each got.

#209 Add email migration endpoints
  app/app.py
  app/cruds/cruds_users.py
  app/endpoints/users.py
  app/models/models_core.py
  app/schemas/schemas_core.py
  app/utils/tools.py
  requirements-dev.txt
  tests/commons.py
  tests/test_users.py
Labels: ready for review, feat

#232 get_file_from_data mitigation
  app/endpoints/campaign.py
  app/endpoints/cinema.py
  app/endpoints/core.py
  app/endpoints/raffle.py
  app/endpoints/users.py
  app/utils/tools.py
Labels: ready for review, fix bug

#233 Fix email regex
  app/endpoints/users.py
  app/utils/types/groups_type.py
Labels: ready for review, fix bug, feat

#236 Module visibility
  app/api.py
  app/app.py
  app/cruds/cruds_core.py
  app/endpoints/core.py
  app/models/models_core.py
  app/schemas/schemas_core.py
  app/utils/types/module.py
  app/utils/types/module_list.py
  app/utils/types/router.py
  tests/test_core.py
Labels: enhancement, core, ready for review, feat

#212 Fix open redirect vulnerability
  .env.test
  app/core/config.py
  app/endpoints/auth.py
  app/utils/auth/providers.py
Labels: ready for review, fix bug

#178 Notification
  .env
  .env.test
  .gitignore
  README.md
  app/api.py
  app/core/config.py
  app/cruds/cruds_cinema.py
  app/cruds/cruds_notification.py
  app/dependencies.py
  app/endpoints/cinema.py
  app/endpoints/notification.py
  app/models/models_notification.py
  app/schemas/schemas_notification.py
  app/utils/communication/notifications.py
  app/utils/types/notification_types.py
  app/utils/types/tags.py
  docker-compose.yaml
  requirements.txt
Labels: notifications, ready for review, feat

#138 Advert module
  app/api.py
  app/cruds/cruds_advert.py
  app/endpoints/advert.py
  app/models/models_advert.py
  app/schemas/schemas_advert.py
  app/utils/types/tags.py
  assets/images/default_advert.png
  tests/test_advert.py
Labels: module, ready for review
