Repository aeecleclair/Hyperion, pull requests merged in 2023-01, with the labels that each got.

#99 Add count users' endpoint
  app/cruds/cruds_users.py
  app/endpoints/users.py
Labels: core

#62 Campaign module
  app/api.py
  app/cruds/cruds_campaign.py
  app/endpoints/campaign.py
  app/endpoints/groups.py
  app/endpoints/users.py
  app/main.py
  app/models/models_campaign.py
  app/schemas/schemas_campaign.py
  app/schemas/schemas_core.py
  app/utils/tools.py
  app/utils/types/campaign_type.py
  app/utils/types/groups_type.py
  app/utils/types/tags.py
  assets/images/default_campaigns_logo.png
  docs/modules/campaign.md
  tests/test_campaign.py
Labels: module

#111 Synapse auth provider
  app/utils/auth/providers.py
  app/utils/tools.py
  requirements.txt
Labels: authentication

#83 Movies
  app/api.py
  app/cruds/cruds_cinema.py
  app/endpoints/cinema.py
  app/models/models_cinema.py
  app/schemas/schemas_cinema.py
  app/utils/types/groups_type.py
  app/utils/types/tags.py
  assets/images/default_movie.png
  requirements.txt
  tests/test_cinema.py
Labels: module

#112 Core User creation promo and floor
  app/endpoints/users.py
  app/models/models_core.py
  app/schemas/schemas_core.py
  app/utils/examples/examples_core.py
  app/utils/types/floors_type.py
  app/utils/validators.py
  tests/commons.py
  tests/test_auth.py
  tests/test_users.py
Labels: core

#96 Improve logging
  app/core/log.py
  app/endpoints/auth.py
  app/endpoints/groups.py
  app/main.py
  app/utils/loggers_tools/matrix_handler.py
Labels: core, logging

#114 Fix loans endpoints permissions
  app/endpoints/loans.py
Labels: bug
