Repository aeecleclair/Hyperion, pull requests merged in 2024-08, with the labels that each got.

#494 Add colors to different levels of log in console
  app/core/log.py
  requirements-dev.txt
Labels: enhancement, logging

#493 Bump ruff to version 0.5.2
  pyproject.toml
  requirements-dev.txt
Labels: dependencies, python

#439 Init payment with HelloAsso
  .env.template
  app/api.py
  app/core/config.py
  app/core/payment/__init__.py
  app/core/payment/cruds_payment.py
  app/core/payment/endpoints_payment.py
  app/core/payment/models_payment.py
  app/core/payment/payment_tool.py
  app/core/payment/schemas_payment.py
  app/dependencies.py
  app/module.py
  app/types/exceptions.py
  app/types/module.py
  migrations/versions/16-Payment.py
  requirements-common.txt
  tests/test_payment.py
Labels: core, payment

#504 Drop all tables based on db schema instead of models
  app/app.py
Labels: core, fix bug, startup

#480 Validate phone number on user creation and update
  app/core/schemas_core.py
  app/utils/validators.py
  requirements-common.txt
Labels: enhancement, core

#465 Support oauth-authorization-server wellknown discovery and simplify dotenv config
  .env.template
  .env.test
  app/core/auth/endpoints_auth.py
  app/core/config.py
  tests/test_auth.py
Labels: enhancement, core, authentication

#458 Add ContentHTTPException and AuthHTTPException
  app/app.py
  app/core/auth/endpoints_auth.py
  app/types/exceptions.py
Labels: enhancement, core, authentication

#477 Fix loggers and db initialization when using multiple Gunicorn workers
  Dockerfile
  README.md
  app/app.py
  app/core/config.py
  app/dependencies.py
  docker-compose.yaml
  gunicorn.conf.py
Labels: enhancement, core, fix bug

#507 Enable new rules for Ruff
  app/core/auth/cruds_auth.py
  app/core/auth/endpoints_auth.py
  app/core/config.py
  app/core/cruds_core.py
  app/core/groups/cruds_groups.py
  app/core/notification/cruds_notification.py
  app/core/payment/cruds_payment.py
  app/core/payment/endpoints_payment.py
  app/core/payment/payment_tool.py
  app/core/users/cruds_users.py
  app/core/users/endpoints_users.py
  app/dependencies.py
  app/modules/advert/endpoints_advert.py
  app/modules/amap/cruds_amap.py
  app/modules/amap/endpoints_amap.py
  app/modules/booking/cruds_booking.py
  app/modules/calendar/cruds_calendar.py
  app/modules/campaign/cruds_campaign.py
  app/modules/campaign/endpoints_campaign.py
  app/modules/cinema/endpoints_cinema.py
  app/modules/flappybird/cruds_flappybird.py
  app/modules/loan/cruds_loan.py
  app/modules/loan/endpoints_loan.py
  app/modules/ph/cruds_ph.py
  app/modules/raffle/cruds_raffle.py
  app/modules/raffle/endpoints_raffle.py
  app/types/core_data.py
  app/types/exceptions.py
  app/types/sqlalchemy.py
  app/utils/communication/matrix.py
  app/utils/communication/notifications.py
  app/utils/initialization.py
  app/utils/tools.py
  app/utils/validators.py
  migrations/env.py
  pyproject.toml
  tests/commons.py
  tests/test_advert.py
  tests/test_auth.py
  tests/test_calendar.py
  tests/test_campaign.py
  tests/test_migrations.py
  tests/test_payment.py
  tests/test_utils.py
Labels: enhancement, code quality

#515 Init db engine on Hyperion launch
  app/app.py
  app/dependencies.py
  migrations/env.py
Labels: core, fix bug, startup

#525 Create auth utils to get data from token and user from token data
  app/dependencies.py
  app/utils/auth/auth_utils.py
Labels: enhancement, authentication

#529 Drop test db before migration tests
  app/app.py
  app/utils/initialization.py
  tests/test_migrations.py
Labels: core, fix bug, test

#446 Reception Route Module (CDR)
  app/app.py
  app/core/config.py
  app/core/groups/groups_type.py
  app/core/models_core.py
  app/core/security.py
  app/core/users/cruds_users.py
  app/core/users/endpoints_users.py
  app/dependencies.py
  app/modules/cdr/__init__.py
  app/modules/cdr/cruds_cdr.py
  app/modules/cdr/endpoints_cdr.py
  app/modules/cdr/models_cdr.py
  app/modules/cdr/schemas_cdr.py
  app/modules/cdr/types_cdr.py
  app/modules/cdr/utils_cdr.py
  app/types/membership.py
  app/types/websocket.py
  app/utils/auth/providers.py
  app/utils/mail/mailworker.py
  app/utils/tools.py
  gunicorn.conf.py
  migrations/versions/17-external_user_email_migration.py
  migrations/versions/18-reception_route.py
  requirements-common.txt
  tests/test_cdr.py
Labels: module, ready for review

#495 Send an email when recovering an account that does not exist
  app/core/users/endpoints_users.py
  assets/templates/reset_mail_does_not_exist.html
  tests/test_users.py
Labels: enhancement, jinja

#532 Use model_fields_set to check if at least a field is to be updated
  app/modules/cdr/cruds_cdr.py
  app/modules/cdr/endpoints_cdr.py
  app/modules/recommendation/cruds_recommendation.py
Labels: bug

#510 Google API
  .env.template
  README.md
  app/core/config.py
  app/core/endpoints_core.py
  app/types/exceptions.py
  app/utils/google_api/README.md
  app/utils/google_api/__init__.py
  app/utils/google_api/coredata_google_api.py
  app/utils/google_api/google_api.py
  pyproject.toml
  requirements-common.txt
Labels: enhancement, core

#347 Module/raid registering
  app/core/auth/endpoints_auth.py
  app/core/config.py
  app/core/groups/groups_type.py
  app/core/payment/endpoints_payment.py
  app/dependencies.py
  app/modules/cdr/models_cdr.py
  app/modules/raid/__init__.py
  app/modules/raid/coredata_raid.py
  app/modules/raid/cruds_raid.py
  app/modules/raid/endpoints_raid.py
  app/modules/raid/models_raid.py
  app/modules/raid/raid_type.py
  app/modules/raid/schemas_raid.py
  app/modules/raid/utils/__init__.py
  app/modules/raid/utils/drive/__init__.py
  app/modules/raid/utils/drive/drive_file_manager.py
  app/modules/raid/utils/pdf/__init__.py
  app/modules/raid/utils/pdf/conversion_utils.py
  app/modules/raid/utils/pdf/pdf_writer.py
  app/modules/raid/utils/utils_raid.py
  app/utils/auth/providers.py
  assets/templates/style.css
  assets/templates/template.html
  migrations/versions/19-raid_registering.py
  requirements-common.txt
  requirements-dev.txt
  tests/commons.py
  tests/conftest.py
  tests/test_cdr.py
  tests/test_raid.py
Labels: module

#534 Allow external users from online endpoints
  app/modules/cdr/endpoints_cdr.py
Labels: fix bug, cdr

#535 Bump version 2.9.0
  app/core/config.py
Labels: release

#538 Endpoint permission and product variant deactivation
  app/modules/cdr/endpoints_cdr.py
  tests/test_cdr.py
Labels: cdr

#537 Change customdata link from seller to product
  app/modules/cdr/cruds_cdr.py
  app/modules/cdr/endpoints_cdr.py
  app/modules/cdr/models_cdr.py
  app/modules/cdr/schemas_cdr.py
  migrations/versions/20-cdr_customdata.py
  tests/commons.py
  tests/test_cdr.py
Labels: cdr

#539 Bump version 2.9.1
  app/core/config.py
Labels: release

#543 CDR: Allow to update promo, birthday and phone
  app/modules/cdr/schemas_cdr.py
  tests/test_cdr.py
Labels: cdr

#547 Remove ws connection after unsubscribe
  app/modules/cdr/endpoints_cdr.py
  app/types/websocket.py
Labels: bug, cdr

#548 Bump version 2.9.3
  app/core/config.py
Labels: release

#550 Allow external users for RaidRegistering auth client
  app/utils/auth/providers.py
Labels: fix bug, raid registering

#551 Release 2.9.4
  app/core/config.py
Labels: release
