Repository aeecleclair/Hyperion, pull requests merged in 2024-02, with the labels that each got.

#311 OIDC improvements
  .env.test
  app/core/security.py
  app/endpoints/auth.py
  app/schemas/schemas_auth.py
  app/utils/auth/providers.py
  app/utils/types/scopes_type.py
  tests/test_auth.py
Labels: authentication

#322 Fix cinema notification
  app/endpoints/booking.py
Labels: bug

#321 Make TopicMembership's topic_identifier non nullable
  app/models/models_notification.py
  app/utils/types/notification_types.py
Labels: don't merge

#312 Run Alembic migrations on Hyperion startup
  alembic.ini
  app/app.py
  app/models/models_core.py
  migrations/env.py
  migrations/script.py.mako
  migrations/versions/0-init.py
  migrations/versions/1-booking_enhancements.py
Labels: core, ready for review

#333 Fix black formatting
  .vscode/settings.json
  app/core/config.py
Labels: ready for review

#336 Fix migrations & initializations when using multiple workers
  README.md
  app/app.py
  app/cruds/cruds_core.py
  app/dependencies.py
  app/utils/initialization.py
  docker-compose.yaml
  requirements.txt
Labels: ready for review

#281 feat: support Pydantic V2
  app/app.py
  app/core/config.py
  app/core/security.py
  app/cruds/cruds_advert.py
  app/cruds/cruds_amap.py
  app/cruds/cruds_booking.py
  app/cruds/cruds_calendar.py
  app/cruds/cruds_campaign.py
  app/cruds/cruds_cinema.py
  app/cruds/cruds_groups.py
  app/cruds/cruds_loan.py
  app/cruds/cruds_raffle.py
  app/cruds/cruds_users.py
  app/endpoints/advert.py
  app/endpoints/amap.py
  app/endpoints/booking.py
  app/endpoints/calendar.py
  app/endpoints/campaign.py
  app/endpoints/cinema.py
  app/endpoints/loan.py
  app/endpoints/raffle.py
  app/models/models_loan.py
  app/schemas/schemas_advert.py
  app/schemas/schemas_amap.py
  app/schemas/schemas_auth.py
  app/schemas/schemas_booking.py
  app/schemas/schemas_calendar.py
  app/schemas/schemas_campaign.py
  app/schemas/schemas_cinema.py
  app/schemas/schemas_core.py
  app/schemas/schemas_loan.py
  app/schemas/schemas_notification.py
  app/schemas/schemas_raffle.py
  app/utils/communication/notifications.py
  app/utils/examples/examples_core.py
  migrations/versions/3-pydantic_v2.py
  requirements.txt
  tests/commons.py
  tests/test_loan.py
Labels: dependencies
