Repository aeecleclair/Hyperion, pull requests merged in 2024-06, with the labels that each got.

#460 Send cinema and loan notifications at the right delivery_datetime
  app/modules/cinema/endpoints_cinema.py
  app/modules/loan/endpoints_loan.py
  app/utils/communication/date_manager.py
Labels: bug, notifications

#453 Remove unused parameters
  app/core/users/endpoints_users.py
  app/dependencies.py
  app/modules/booking/endpoints_booking.py
  app/modules/campaign/endpoints_campaign.py
  app/modules/loan/endpoints_loan.py
  app/modules/recommendation/endpoints_recommendation.py
Labels: ready for review

#468 Replacing IMDb with TMDb
  .env.template
  .env.test
  app/core/config.py
  app/modules/cinema/endpoints_cinema.py
Labels: cinema

#473 Bump version 2.5.3-alpha
  app/core/config.py
Labels: release

#476 Bump version 2.5.4
  app/core/config.py
Labels: release

#469 Improve auth test coverage and fix errors
  .env.test
  app/core/auth/endpoints_auth.py
  app/core/users/cruds_users.py
  tests/test_auth.py
Labels: authentication, test

#478 Bump version 2.5.5
  app/core/config.py
Labels: release

#450 Use postgresql for tests
  .env.test
  .github/workflows/test.yml
  .gitignore
  migrations/versions/0-6-init.py
  migrations/versions/8-recommendation_primary_key.py
  migrations/versions/9-external_users.py
  pyproject.toml
  tests/commons.py
  tests/conftest.py
  tests/test_PH.py
  tests/test_advert.py
  tests/test_amap.py
  tests/test_auth.py
  tests/test_booking.py
  tests/test_calendar.py
  tests/test_campaign.py
  tests/test_cinema.py
  tests/test_core.py
  tests/test_flappybird.py
  tests/test_groups.py
  tests/test_loan.py
  tests/test_migrations.py
  tests/test_notification.py
  tests/test_phonebook.py
  tests/test_raffle.py
  tests/test_ratelimit.py
  tests/test_recommendation.py
  tests/test_users.py
  tests/test_utils.py
Labels: enhancement, core

#338 Add token introspection endpoint
  .env.test
  app/core/auth/endpoints_auth.py
  app/core/auth/schemas_auth.py
  app/dependencies.py
  app/utils/auth/providers.py
  tests/commons.py
  tests/test_auth.py
Labels: enhancement, core, authentication

#482 Bump version 2.6.0
  app/core/config.py
Labels: release

#470 Calypsso
  app/app.py
  app/core/auth/endpoints_auth.py
  app/core/auth/schemas_auth.py
  app/core/users/endpoints_users.py
  assets/templates/activation.html
  assets/templates/activation_mail.html
  assets/templates/connexion.html
  assets/templates/error.html
  assets/templates/reset_mail.html
  requirements-common.txt
  tests/test_auth.py
Labels: enhancement
