Repository aeecleclair/Hyperion, pull requests merged in 2024-11, with the labels that each got.

#516 Add Documenso provider
  .env.template
  app/core/auth/endpoints_auth.py
  app/core/groups/groups_type.py
  app/utils/auth/providers.py
  migrations/versions/25-hardcode-eclair-group.py
  pyproject.toml
  tests/test_auth.py
  tests/test_groups.py
Labels: enhancement, authentication

#605 Notification without token
  app/utils/communication/notifications.py
Labels: notifications, fix bug

#552 Raise ValueError in phone validator
  app/types/exceptions.py
  app/utils/validators.py
  tests/test_users.py
Labels: core, fix bug

#618 Bump CalypSSO to 1.2.0
  requirements-common.txt
Labels: dependencies, python

#619 Restrict Overleaf auth client to ecl users
  app/utils/auth/providers.py
Labels: authentication
