Repository aeecleclair/Hyperion, pull requests merged in 2025-08, with the labels that each got.

#789 Restrict advert picture addition to managers of the advertiser
  app/modules/advert/endpoints_advert.py
Labels: fix bug, advert

#794 Hyperion 4.7.0
  pyproject.toml
Labels: release

#810 Bump version
  pyproject.toml
Labels: ready for review, release, cdr
